# Standalone doesn't support admin mode which only works with etcd
apisix:
  ssl:
    cert: -----BEGIN CERTIFICATE----- MIICrTCCAZUCFHZdggoCWdDBTwNZLX+d7c2j9IIvMA0GCSqGSIb3DQEBCwUAMBEx DzANBgNVBAMMBlJPT1RDQTAgFw0yNTA0MTkyMTE0MTJaGA8yMTI1MDMyNjIxMTQx MlowEzERMA8GA1UEAwwIdGVzdC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw ggEKAoIBAQCQ0TElOQwmqjSdW0jReIDMaDILL+pkgFwn5YfZUpfXwUNWYICdhLy0 W+IBHUtftXB1fjWgOipqyrmJeXVgNjClyHX3PehyNFaqeMFOuco461749g6TnEjL WxE0HijyYTBFW+chfh4+sUc1Zyla0lQ1e32lfCaZiQ5O2jZP1LxEeKdeXFhaxtTh Gj/kqU8IxAZiqKpy/yQUX7R8Xb76hJkDEWIejCCWta4+eiafk1e7+JDJAE+u/af7 jGm01JLxW4bIJzqyKqS7t7IyTGTVnTKsqObY7a26/eDKgOrixuoQbECVzyxv8F1z RYX0ZOgDAdy1SxXzcxhSX7lqMBYwx5lzAgMBAAEwDQYJKoZIhvcNAQELBQADggEB ADKcDMW2WSDNEX1/VvvRUlKaJVVV36vNyD02mdGDtg74pQjjptAB2ajA1dNGRvfb F3DPhJMEHNnfBMB6Ghn4381jp1UqdBcXnuw+7zAhN2/jhbyjeeUY9u034k0o3ran 35Jnf/+nXramV9aEsBeBYM11J1hOdtBvW44jJ8GGRE5Kj/5xFR+GD0J/A3Eg+sDe aQur1sGWzjsUJt08+LLtuhUP1zPITc1x6wdUuBIjQ13LBZ/qQX9eEaluW+Yoih4k loYqB9e7InYG142skf4wGGYeSkM14nmfy43a6uSdGs384OTuoC1xzKw8XFMRCpYb bHUiUaiBkIdh3MHXoqeOQSo= -----END CERTIFICATE-----
    key: -----BEGIN PRIVATE KEY----- MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCQ0TElOQwmqjSd W0jReIDMaDILL+pkgFwn5YfZUpfXwUNWYICdhLy0W+IBHUtftXB1fjWgOipqyrmJ eXVgNjClyHX3PehyNFaqeMFOuco461749g6TnEjLWxE0HijyYTBFW+chfh4+sUc1 Zyla0lQ1e32lfCaZiQ5O2jZP1LxEeKdeXFhaxtThGj/kqU8IxAZiqKpy/yQUX7R8 Xb76hJkDEWIejCCWta4+eiafk1e7+JDJAE+u/af7jGm01JLxW4bIJzqyKqS7t7Iy TGTVnTKsqObY7a26/eDKgOrixuoQbECVzyxv8F1zRYX0ZOgDAdy1SxXzcxhSX7lq MBYwx5lzAgMBAAECggEAIDG5XL6RcnkNSFw2VIcXDxos4erNj3kvw5jV+hzP7+Gh oC7E+P+82dXBaSEDlCvoa95aepvjuSkHVUYgr3pslzZ47zWemuEC0VQWGXPZPo0o 6Gz/MZahYkAFE5KO5M9xZUH4oKwCekp7+6XK/kta+CbTeHogtKpQ+XuublHrZscc OMk6J0xLEI5LD/srzZgO4N6cFIbSHfWDoUbudN7ACkZZERpSfhjrnWOnWF8KmWdT QxXQNwgmfB8gaDM8rEBG3O/rxgjNJgDPwLUSFlDyWp7kZzNrcCaVjDyjqQBHZ/sY jAQElWELFFwHVUTLlknY0S206gambSLsue4I85De9QKBgQDHWjKEop08MRBjz65y 3c4+Pm+3xcRYqB2e6OcQHPRS/lsn6Wzl45XPJYUzKh4m3rt1AXu8lPdO41qof4Ss lotVYd8oJyWNK6ovrIpZpb0pL30gGEw9NywbFn9Hj4M84X7pdjaaHxcLn9fMoGji 0kyzszx6k79544SHS2/6tKq8JwKBgQC599sXt/Gb5+Gp//qA7Q0gE5v8zc7WDqNG xQM6oNov8ufXfGjHlcPUwqTDCGfYpDRocWj7okx28VoP3h9cv37mIW79BzgG6uvx 4MmTkyIDVELxeX9rcchOjIMsQNMgnHJjGJfC9DrtUB51PoKvxIHDZ08rddlD9sUq Cj/S7H2r1QKBgCIESyCE2w29VY2ij6L8JEhMwSV7srBqJ3vJRDxkpHBRBN7/ntxv hE2vmlYLts9tLFGf6ixYwwaMFxkvgUUt/yKXq8ufOnInZEf0SjtX47pWZySF4OSF OJp6sUdVvtAxrkVKLbEI4xbRtLIvIRarSflT+Vr1QTQcVa38emQuVf/7AoGAdtsg njIkKz6yjdJaqlfXUa72vUZUcZ79X9e+zpPLn2WiI6kR1q2zcaHNaBFRPbcE/9Os A1ehg0uSAh428TI6yp6HrxQUDOfMUNUYQEeDL5mFB4xdkbAxE3Ley0PLLEaRHSC0 rhcmKlJQhSKkp+3x+Y9nnCE/8R4guVO/ovEfCNkCgYA/IcxIVjzQJ7zVEnLy9kgl 7jsKwI83TIfsBoU0lTeQr96ENxW/4LN5ixaz6a1bK1xUezwFuJSFARhwpacEjnMa b+heGO14GujrCM6jEJzHcpPBuukgwao3255VU4doA0D43GwjsmCyvo6k7+c1/JUG Jp4LPmi3+6I7HkXdgR99wg== -----END PRIVATE KEY-----
    snis: test.com
    ssl_protocols: TLSv1.2 TLSv1.3 # default TLSv1.2 TLSv1.3
    # ssl_ciphers is for reference only
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA
  extra_lua_path: "/usr/local/apisix/apisix/dspai_plugins/?.lua"

deployment:
  role: data_plane #for standalone mode
  role_data_plane:
    config_provider: yaml  #for standalone mode

plugins:
  - file-logger
  - real-ip                        # priority: 23000
  - ai                             # priority: 22900
  - client-control                 # priority: 22000
  - proxy-control                  # priority: 21990
  - request-id                     # priority: 12015
  - zipkin                         # priority: 12011
  #- skywalking                    # priority: 12010
  #- opentelemetry                 # priority: 12009
  - ext-plugin-pre-req             # priority: 12000
  - fault-injection                # priority: 11000
  - mocking                        # priority: 10900
  - serverless-pre-function        # priority: 10000
  #- batch-requests                # priority: 4010
  - cors                           # priority: 4000
  - ip-restriction                 # priority: 3000
  - ua-restriction                 # priority: 2999
  - referer-restriction            # priority: 2990
  - csrf                           # priority: 2980
  - uri-blocker                    # priority: 2900
  - request-validation             # priority: 2800
  - chaitin-waf                    # priority: 2700
  - openid-connect                 # priority: 2599
  - cas-auth                       # priority: 2597
  - authz-casbin                   # priority: 2560
  - authz-casdoor                  # priority: 2559
  - wolf-rbac                      # priority: 2555
  - ldap-auth                      # priority: 2540
  - hmac-auth                      # priority: 2530
  - basic-auth                     # priority: 2520
  - jwt-auth                       # priority: 2510
  - key-auth                       # priority: 2500
  - consumer-restriction           # priority: 2400
  - forward-auth                   # priority: 2002
  - opa                            # priority: 2001
  - authz-keycloak                 # priority: 2000
  #- error-log-logger              # priority: 1091
  - proxy-cache                    # priority: 1085
  - body-transformer               # priority: 1080
  - proxy-mirror                   # priority: 1010
  - proxy-rewrite                  # priority: 1008
  - workflow                       # priority: 1006
  - api-breaker                    # priority: 1005
  - limit-conn                     # priority: 1003
  - limit-count                    # priority: 1002
  - limit-req                      # priority: 1001
  #- node-status                   # priority: 1000
  #- data-dome
  - gzip                           # priority: 995
  - server-info                    # priority: 990
  - traffic-split                  # priority: 966
  - redirect                       # priority: 900
  - response-rewrite               # priority: 899
  - degraphql                      # priority: 509
  - kafka-proxy                    # priority: 508
  #- dubbo-proxy                   # priority: 507
  - grpc-transcode                 # priority: 506
  - grpc-web                       # priority: 505
  - public-api                     # priority: 501
  - prometheus                     # priority: 500
  - datadog                        # priority: 495
  - loki-logger                    # priority: 414
  - elasticsearch-logger           # priority: 413
  - echo                           # priority: 412
  - loggly                         # priority: 411
  - http-logger                    # priority: 410
  - splunk-hec-logging             # priority: 409
  - skywalking-logger              # priority: 408
  - google-cloud-logging           # priority: 407
  - sls-logger                     # priority: 406
  - tcp-logger                     # priority: 405
  - kafka-logger                   # priority: 403
  - rocketmq-logger                # priority: 402
  - syslog                         # priority: 401
  - udp-logger                     # priority: 400
  - file-logger                    # priority: 399
  - clickhouse-logger              # priority: 398
  - tencent-cloud-cls              # priority: 397
  - inspect                        # priority: 200
  - aws-lambda                     # priority: -1899
  - azure-functions                # priority: -1900
  - openwhisk                      # priority: -1901
  - openfunction                   # priority: -1902
  - serverless-post-function       # priority: -2000
  - ext-plugin-post-req            # priority: -3000
  - ext-plugin-post-resp           # priority: -4000

#END